apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seki.fullname" . }}-secret
  labels:
    {{- include "seki.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.signingKey }}
  signing-key: {{ .Values.signingKey | b64enc | quote }}
  {{- else }}
  signing-key: {{ "" | b64enc | quote }}
  {{- end }}
  {{- if .Values.apiKeys }}
  {{- range $i, $key := .Values.apiKeys }}
  api-key-{{ $i }}: {{ $key | b64enc | quote }}
  {{- end }}
  {{- end }}
